apiVersion: v1
kind: Service
metadata:
  name: emailservice
spec:
  selector:
    app: emailservice
  ports:
    - protocol: TCP
      port: 80
{{ if eq .Values.werf.env "dev" }}      
      targetPort: 80
      nodePort: 30004
  type: NodePort
{{ end }} 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailservice-deployment
  labels:
    app: emailservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emailservice
  template:
    metadata:
      labels:
        app: emailservice
    spec:
      containers:
      - name: emailservice
        image: {{ .Values.werf.image.emailservice }}
        ports:
        - containerPort: 80
        env:
        - name: PORT
          value: "80"
        imagePullPolicy: Always
        