apiVersion: v1
kind: Service
metadata:
  name: shippingservice
spec:
  selector:
    app: shippingservice
  ports:
    - protocol: TCP
      port: 80
{{ if eq .Values.werf.env "dev" }}      
      targetPort: 80
      nodePort: 30005
  type: NodePort
{{ end }}  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shippingservice-deployment
  labels:
    app: shippingservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shippingservice
  template:
    metadata:
      labels:
        app: shippingservice
    spec:
      containers:
      - name: shippingservice
        image: {{ .Values.werf.image.shippingservice }}
        ports:
        - containerPort: 80
        env:
        - name: PORT
          value: "80"
        imagePullPolicy: Always
        