apiVersion: v1
kind: Service
metadata:
  name: checkoutservice
spec:
  selector:
    app: checkoutservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkoutservice-deployment
  labels:
    app: checkoutservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkoutservice
  template:
    metadata:
      labels:
        app: checkoutservice
    spec:
      containers:
      - name: checkoutservice
        image: {{ .Values.werf.image.checkoutservice }}
        ports:
        - containerPort: 80
        env:
          - name: CARTSERVICE
            value: "http://cartservice:80"
          - name: EMAILSERVICE
            value: "http://emailservice:80"
          - name: PAYMENTSERVICE
            value: "http://paymentservice:80"
          - name: SHIPPINGSERVICE
            value: "http://shippingservice:80"
          - name: PRODUCTSERVICE
            value: "http://productservice:80"
        imagePullPolicy: Always
        