apiVersion: v1
kind: Service
metadata:
  name: cartservice
spec:
  selector:
    app: cartservice
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice-deployment
  labels:
    app: cartservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cartservice
  template:
    metadata:
      labels:
        app: cartservice
    spec:
      containers:
      - name: cartservice
        image: {{ .Values.werf.image.cartservice }}
        ports:
        - containerPort: 8081
        env:
          - name: REDIS_HOST
            value: "cartservice-redis:6379"
        imagePullPolicy: Always
        # livenessProbe:
        #   httpGet:
        #     path: /health
        #     port: 8081
        #     initialDelaySeconds: 10
        #     periodSeconds: 10
