apiVersion: v1
kind: Service
metadata:
  name: frontendservice
spec:
  selector:
    app: frontendservice
  ports:
    - protocol: TCP
      port: 80
{{ if eq .Values.werf.env "dev" }}
      targetPort: 80
      nodePort: 30003
  type: NodePort
{{ else }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontendservice-deployment
  labels:
    app: frontendservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontendservice
  template:
    metadata:
      labels:
        app: frontendservice
    spec:
      containers:
      - name: frontendservice
        image: {{ .Values.werf.image.frontendservice }}
        ports:
        - containerPort: 80
        env:
          - name: CARTSERVICE
            value: "http://cartservice:80"
          - name: PRODUCTSERVICE
            value: "http://productservice:80"
          - name: CHECKOUTSERVICE
            value: "http://checkoutservice:80"
        imagePullPolicy: Always
        