apiVersion: v1
kind: Service
metadata:
  name: frontendservice
spec:
  selector:
    app: frontendservice
  ports:
    - name: frontendservice
      port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontendservice-deployment
  labels:
    app: frontendservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontendservice
  template:
    metadata:
      labels:
        app: frontendservice
    spec:
      containers:
      - name: frontendservice
        image: {{ .Values.werf.image.frontendservice }}
        ports:
        - containerPort: 80
        env:
          - name: CARTSERVICE
            value: "http://cartservice:8081"
          - name: PRODUCTSERVICE
            value: "http://productservice:80"
          - name: CHECKOUTSERVICE
            value: "http://checkoutservice:8080"
        imagePullPolicy: Always
        