apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bfmarket-app
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
{{ if eq .Values.werf.env "prod" }}
  - host: example.com
{{ else }}
  - host: {{ .Values.werf.env }}.example.com
{{ end }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontendservice
            port:
              number: 80
